# Title shown in Application Information tab.
title: Autonomous Database Shared Schema
# Sub Title shown in Application Information tab.
description: Stack deploys a Autonoumous Database Shared instance. By default parameters are based on Free Tier limitations. In order to deploy a non-Free Tier instance select Advanced Options.
informationalText: Stack deploys a Autonoumous Database Shared instance. By default parameters are based on Free Tier limitations.
schemaVersion: 1.0.0
version: "20210715"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace 
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the 
# "marketplace-listing-id" tag for the same purpose.
# source:
#   type: marketplace
#   reference: 16132843

locale: "en"
variableGroups:
  - title: "Database"
    #visible: true
    variables:
      - ${compartment_ocid}
      - ${owner}
      - ${project}
      - ${advanced_adb_options}
      - ${object_storage_options}
      - ${network_options}

  - title: "Advanced Database Options"
    visible:
      or:
        - ${advanced_adb_options}
    variables:
      - ${workload_type}
      - ${db_version}
      - ${cpu_core_count}
      - ${data_storage_tbs}
      - ${autoscaling_enabled}

  - title: "Object Storage Options"
    visible:
      or:
        - ${object_storage_options}
    variables:
      - ${object_storage}
        
  - title: "Network Options"
    visible:
      or:
        - ${network_options}
    variables:
      - ${nw_compartment_ocid}
      - ${vcn_id}
      - ${subnet_id}
      - ${whitelisted_ips}
      - ${nsg_id}

  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "region"


variables:

  compartment_ocid:
    title: "Compartment OCID"
    type: oci:identity:compartment:id

  owner:
    required: true
    type: string
    title: "Owner"
    description: "Owner"
    pattern: "^[a-zA-z1-9]{1,5}$"
    default: ""

  project:
    required: true
    type: string
    title: "Project"
    description: "Project"
    pattern: "^[a-zA-z1-9]{1,5}$"
    default: ""

  advanced_adb_options:
    title: "Advanced Database Options"
    type: boolean

  object_storage_options:
    title: "Object Storage Options"
    type: boolean

  network_options:
    title: "Network Options"
    type: boolean

  cpu_core_count:
    title: "Core OCPU Count"
    required: true
    type: integer
    default: 1
    minimum: 1
    maximum: 128
    description: "Number of OCPUs. In case auto scaling is enabled, database can use up to 3 times number of OCPUs"

  data_storage_tbs:
    title: "Database Storage(TB)"
    required: true
    type: integer
    default: 1
    minimum: 1
    maximum: 128
    description: "Database Storage in TB."

  autoscaling_enabled:
    title: "Auto Scaling Enabled"
    type: boolean
    description: "Enable Auto Scaling"

  workload_type:
    type: enum
    title: "Workload Type"
    description: "Workload Type"
    enum:
      - "OLTP"
      - "DW"
      - "AJD"
      - "APEX"

  db_version:
    title: "Database Version"
    type: oci:database:autonomousdatabaseversion:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      dbWorkload: ${workload_type}

  object_storage:
    title: "Setup Object Storage"
    type: boolean
    description: "Setup Object Storage"

  nw_compartment_ocid:
    title: "Network Compartment OCID"
    type: oci:identity:compartment:id

  vcn_id:
    title: "VCN for private Endpoint"
    type: oci:core:vcn:id
    description: "VNC where the private Access Endpoint will be created"
    dependsOn:
      compartmentId: ${nw_compartment_ocid}
  
  subnet_id:
    title: "Subnet for private Endpoint"
    type: oci:core:subnet:id
    description: "Private subnet used to create a private Access Endpoint"
    dependsOn:
      compartmentId: ${nw_compartment_ocid}
      vcnId: ${vcn_id}
      hidePublicSubnet: true

  nsg_id:
    title: "Database Network Security Group"
    type: oci:core:nsg:id
    dependsOn:
      vcnId: ${vcn_id}
      compartmentId: ${nw_compartment_ocid}

  whitelisted_ips:
    title: "Access control list (ACL)"
    description: "The client IP access control list (ACL). Use a semicolon (;) as a deliminator between the VCN-specific subnets or IPs"
    type: array
    items:
      type: string
      pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
    minItems: 0
    uniqueItems: true

# Variables not required to display to user
  user_ocid:
    type: string

  fingerprint:
    type: string

  private_key_path:
    type: string

  region:
    type: string
